# Generated by the Newton Policy Builder
# Goal:     Newton AML/OFAC Policy Engine
# Provider: OpenSanctions (self-hosted yente)
# Reads:    data.wasm.*

package newton_builder_policy

default allow := false

yente_ok if data.wasm.status == 200
payee_screened if data.wasm.to.screened == true
payer_screened if data.wasm.from.screened == true
payee_address_matches if lower(data.wasm.to.address) == lower(input.to)
payer_address_matches if lower(data.wasm.from.address) == lower(input.from)
default min_score := 0
min_score := data.params.min_match_score if is_number(data.params.min_match_score)
payee_hit if {
    data.wasm.to.sanctioned == true
    data.wasm.to.match_score >= min_score
}
payer_hit if {
    data.wasm.from.sanctioned == true
    data.wasm.from.match_score >= min_score
}

deny contains "screening_unavailable" if not yente_ok

deny contains "payee_not_screened" if not payee_screened

deny contains "payer_not_screened" if not payer_screened

deny contains "payee_address_mismatch" if not payee_address_matches

deny contains "payer_address_mismatch" if not payer_address_matches

deny contains "payee_sanctioned" if payee_hit

deny contains "payer_sanctioned" if payer_hit

allow if count(deny) == 0
