/**
 * Load the sanctioned-address list into the denylist PolicyClient's params.
 *
 *   node policy/setparams.mjs                 # dry run, all pool addresses
 *   node policy/setparams.mjs --confirm       # sends
 *   node policy/setparams.mjs --limit 12      # fewer, if the payload is refused
 *
 * WHY THIS EXISTS
 *
 * The yente oracle is unusable right now: Newton's runtime stopped providing
 * `newton:provider/tlsn@0.2.0`, and a policy redeployed to fix that cannot be
 * read by the operators — a freshly pinned CID is fetchable from ipfs.io and
 * Pinata but reports `not found in persisted immutable data backend`. Both
 * blockers are Newton's, and between them there is no working oracle-backed
 * configuration.
 *
 * The denylist policy has neither problem. Its CID was pinned in August and IS
 * in the operator backend — verified by a real quorum-signed task. It has no
 * WASM at all, so there is no component to instantiate and no tlsn to miss.
 * And its address list lives in `policyParams` ON CHAIN, so changing it needs
 * one transaction and no IPFS.
 *
 * WHAT YOU GIVE UP, STATED PLAINLY
 *
 * A static snapshot — currently 97 addresses — not live multi-regime
 * screening. It cannot catch a designation made this morning, and it covers
 * OFAC only: the EU, UN and UK entries the yente feed carries are absent.
 * Anything the demo says about a "consolidated live feed" stops being true
 * while this is bound, and the UI copy must say so. A screen claiming live
 * screening while reading a frozen list is the exact category of lie this
 * project exists to avoid.
 *
 * ON PAYLOAD SIZE
 *
 * `deploy/10-shrink-params.mjs` cut this list from 93 addresses to 3 while
 * debugging a failure — "~4KB → ~0.2KB" — which left a standing belief that a
 * large payload had broken something. It had not. 97 addresses at 4391 bytes
 * were written and verified in one transaction. That script changed
 * `expireAfter` in the same call, so the two hypotheses were never separated
 * and the list stayed small for months on the strength of the wrong one.
 *
 * --limit is kept for bisecting a future failure, and refuses any value that
 * would drop an address the UI can offer.
 */

import { readFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createPublicClient, createWalletClient, http, formatEther, toHex } from "viem";
import { sepolia } from "viem/chains";
import { privateKeyToAccount } from "viem/accounts";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const B = (s) => `\x1b[1m${s}\x1b[0m`;
const RED = (s) => `\x1b[31m${s}\x1b[0m`;

function env(file = join(ROOT, ".env.local")) {
  const out = {};
  if (!existsSync(file)) return out;
  for (const line of readFileSync(file, "utf8").split("\n")) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
    if (m) out[m[1]] = m[2].replace(/^["']|["']$/g, "");
  }
  return out;
}

const E = { ...env(), ...process.env };
const CONFIRM = process.argv.includes("--confirm");
const limitArg = process.argv.indexOf("--limit");
const LIMIT = limitArg > -1 ? Number(process.argv[limitArg + 1]) : Infinity;

const CLIENT = E.POLICY_CLIENT_DENYLIST;
const OWNER_KEY = E.OWNER_PRIVATE_KEY;

if (!CLIENT) {
  console.error("POLICY_CLIENT_DENYLIST is not set in .env.local.");
  process.exit(1);
}
if (!OWNER_KEY) {
  console.error("OWNER_PRIVATE_KEY is not set.  set -a; source ../deploy/.env; set +a");
  process.exit(1);
}

/**
 * Every list we have, deduped, deployed pool-first.
 *
 *   lib/sanctioned-pool.ts   24, live-feed intersection — the ONLY addresses
 *                            the UI's "Sanctioned" button can produce, so they
 *                            must all be in what we write.
 *   lib/ofac-addresses.ts    ~93, from 0xB10C's OFAC digital-currency repo.
 *   lib/ofac-full.ts         the full OFAC ETH set from the live snapshot,
 *                            generated by sanctions-api/emit-full-list.mjs.
 *                            Optional — present only after you run that script.
 *
 * Pool first so that if --limit is needed to stay under block gas, the
 * addresses the demo can actually reach survive the cut. ofac-full is the bulk
 * of the size; it is the "bigger list".
 *
 * Read with a regex rather than imported — these are .ts modules and adding a
 * TypeScript loader to set one contract field is not worth it.
 */
function addressesIn(file) {
  if (!existsSync(join(ROOT, file))) return [];
  return [...readFileSync(join(ROOT, file), "utf8").matchAll(/"(0x[0-9a-fA-F]{40})"/g)].map(
    (m) => m[1],
  );
}

const pool = addressesIn("lib/sanctioned-pool.ts");
const ofac = addressesIn("lib/ofac-addresses.ts");
const ofacFull = addressesIn("lib/ofac-full.ts"); // optional, the big one

const seen = new Set();
const all = [];
for (const a of [...pool, ...ofac, ...ofacFull]) {
  const k = a.toLowerCase();
  if (seen.has(k)) continue;
  seen.add(k);
  all.push(a);
}

if (!pool.length || !all.length) {
  console.error(RED("No addresses found. Refusing to write an empty denylist — the policy"));
  console.error(RED("denies on `denylist_not_configured`, so an empty list would deny every"));
  console.error(RED("transfer and look exactly like screening working."));
  process.exit(1);
}

const addresses = all.slice(0, LIMIT);

/**
 * Every address the "Sanctioned address" button can produce must be in what we
 * write. Miss one and a visitor clicks it, gets COMPLIANT for a real OFAC
 * wallet, and the demo has done the one thing it exists not to do.
 */
const missing = pool.filter((p) => !addresses.some((a) => a.toLowerCase() === p.toLowerCase()));
if (missing.length) {
  console.error(RED(`\n--limit ${LIMIT} drops ${missing.length} address(es) the UI can offer.`));
  console.error(RED("A sanctioned pick would then read COMPLIANT. Raise the limit."));
  process.exit(1);
}
const params = { sanctioned_addresses: addresses };
const policyParams = toHex(new TextEncoder().encode(JSON.stringify(params)));

const ABI = [
  { type: "function", name: "setPolicy", stateMutability: "nonpayable",
    inputs: [{ name: "policyConfig", type: "tuple", components: [
      { name: "policyParams", type: "bytes" },
      { name: "expireAfter", type: "uint32" },
    ] }], outputs: [{ name: "policyId", type: "bytes32" }] },
  { type: "function", name: "getPolicyAddress", stateMutability: "view",
    inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "getPolicyId", stateMutability: "view",
    inputs: [], outputs: [{ type: "bytes32" }] },
  { type: "function", name: "getOwner", stateMutability: "view",
    inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "getPolicyConfig", stateMutability: "view",
    inputs: [{ name: "policyId", type: "bytes32" }],
    outputs: [{ type: "tuple", components: [
      { name: "policyParams", type: "bytes" },
      { name: "expireAfter", type: "uint32" },
    ] }] },
];

const rpc = E.SEPOLIA_RPC_URL || E.RPC_URL || "https://ethereum-sepolia-rpc.publicnode.com";
const account = privateKeyToAccount(OWNER_KEY.startsWith("0x") ? OWNER_KEY : `0x${OWNER_KEY}`);
const pub = createPublicClient({ chain: sepolia, transport: http(rpc) });
const wallet = createWalletClient({ account, chain: sepolia, transport: http(rpc) });

const call = (fn, args) => pub.readContract({ address: CLIENT, abi: ABI, functionName: fn, args });

const [owner, policyAddress, policyId, balance] = await Promise.all([
  call("getOwner"),
  call("getPolicyAddress"),
  call("getPolicyId"),
  pub.getBalance({ address: account.address }),
]);

/**
 * expireAfter is carried across, not re-chosen. It is the one field in this
 * config with a unit ambiguity (the CLI talks in blocks, the chain reports
 * 300) and this script has no business resolving that.
 */
const current = await pub
  .readContract({ address: policyAddress, abi: ABI, functionName: "getPolicyConfig", args: [policyId] })
  .catch(() => null);
const expireAfter = Number(current?.expireAfter ?? current?.[1] ?? 0) || 300;

let currentCount = 0;
let currentSet = null;
try {
  const raw = current?.policyParams ?? current?.[0] ?? "0x";
  const parsed = JSON.parse(Buffer.from(raw.slice(2), "hex").toString("utf8"));
  currentCount = parsed.sanctioned_addresses.length;
  currentSet = new Set(parsed.sanctioned_addresses.map((a) => a.toLowerCase()));
} catch {
  /* unknown — treat as "changed" so a first write always goes through */
}

/**
 * Skip the write when the on-chain list already equals what we would send.
 *
 * The scheduled refresh runs daily but the sanctioned-ETH set moves rarely, so
 * without this every run spends a setPolicy on identical bytes. Compare as
 * lowercased sets — order and case must not count as a change, or the guard
 * never triggers and we pay anyway.
 */
const nextSet = new Set(addresses.map((a) => a.toLowerCase()));
const unchanged =
  currentSet && currentSet.size === nextSet.size && [...nextSet].every((a) => currentSet.has(a));

const bytes = (policyParams.length - 2) / 2;

console.log(`\n${B("Denylist params")}`);
console.log(`  client        ${CLIENT}`);
console.log(`  policy        ${policyAddress}`);
console.log(`  addresses     ${currentCount} -> ${addresses.length}`);
console.log(
  `                ${pool.length} pool, ${ofac.length} 0xB10C, ${ofacFull.length} full-feed (deduped to ${all.length})`,
);
console.log(`  payload       ${bytes} bytes  (~${Math.ceil(bytes / 32)} storage words)`);
if (bytes > 20000) {
  // setPolicy writes the whole blob to on-chain storage at ~20k gas per 32-byte
  // word, so a large list is gas-bound. 4391 bytes (97 addresses) deployed
  // cleanly. Past ~24KB you approach the block gas limit; --limit bisects.
  console.log(RED(`                large — near block-gas territory. If it reverts, --limit.`));
} else if (bytes > 5000) {
  console.log(`                bigger than the 4391 bytes that deployed cleanly, but well`);
  console.log(`                under the gas ceiling. Watch the receipt; --limit if it reverts.`);
}
console.log(`  expireAfter   ${expireAfter}  (carried across)`);
console.log(`\n${B("Signer")}`);
console.log(`  address       ${account.address}`);
console.log(`  client owner  ${owner}`);
console.log(`  balance       ${formatEther(balance)} ETH`);

if (owner.toLowerCase() !== account.address.toLowerCase()) {
  console.error(RED("\nSigner is not the client owner. setPolicy is onlyPolicyClientOwner."));
  process.exit(1);
}

if (unchanged) {
  console.log(`\n${B("No change")} — on-chain list already matches (${addresses.length}). Nothing to send.`);
  process.exit(0);
}

if (!CONFIRM) {
  console.log(`\n${B("First three")}`);
  for (const a of addresses.slice(0, 3)) console.log(`  ${a}`);
  console.log(RED("\nDRY RUN. Nothing sent. Re-run with --confirm.\n"));
  process.exit(0);
}

console.log(`\n${B("setPolicy")}`);
const hash = await wallet.writeContract({
  address: CLIENT, abi: ABI, functionName: "setPolicy",
  args: [{ policyParams, expireAfter }],
});
console.log(`  https://sepolia.etherscan.io/tx/${hash}`);
const receipt = await pub.waitForTransactionReceipt({ hash });
console.log(`  ${receipt.status}`);
if (receipt.status !== "success") process.exit(1);

const newId = await call("getPolicyId");
console.log(`\n  policyId  ${policyId}\n         -> ${newId}`);
console.log("\nVerify with a real task before trusting it:");
console.log(`  curl -sS -X POST https://newton-sanctions-demo.vercel.app/api/evaluate \\`);
console.log(`    -H 'content-type: application/json' \\`);
console.log(`    -d '{"mode":"submit","providerId":"local-denylist","to":"${addresses[0]}"}'`);
console.log("\nevaluation_result all zeros = denied. Then try a clean address and");
console.log("make sure it is ALLOWED — a list that denies everything looks identical");
console.log("to one that works.\n");
