// GENERATED by `node sanctions-api/emit-pool.mjs`. Do not edit.
//
// OFAC-designated Ethereum wallets present in the live OpenSanctions feed
// at generation time. Verified against the same data the deployed policy
// screens against, so every one of these should return NON COMPLIANT.
//
// 24 of 104 OFAC ETH wallets · generated 2026-08-20

export const SANCTIONED_POOL: string[] = [
  "0x175d44451403edf28469df03a9280c1197adb92c",
  "0x35fb6f6db4fb05e6a4ce86f2c93691425626d4b1",
  "0x53b6936513e738f44fb50d2b9476730c0ab3bfc1",
  "0xefe301d259f525ca1ba74a7977b80d5b060b3cca",
  "0xf3701f445b6bdafedbca97d1e477357839e4120d",
  "0x7f19720a857f834887fc9a7bc0a0fbe7fc7f8102",
  "0x2f389ce8bd8ff92de3402ffce4691d17fc4f6535",
  "0x5a7a51bfb49f190e5a6060a5bc6052ac14a3b59f",
  "0xbb69e01921b17cd22080968bcc96ba6115da6062",
  "0x72a5843cc08275c8171e582972aa4fda8c397b2a",
  "0xf4377eda661e04b6dda78969796ed31658d602d4",
  "0x95584c303fcd48af5c6b9873015f2ad0ca84eae3",
  "0xb6f5ec1a0a9cd1526536d3f0426c429529471f40",
  "0x9f4cda013e354b8fc285bf4b9a60460cee7f7ea9",
  "0x5f48c2a71b2cc96e3f0ccae4e39318ff0dc375b2",
  "0xd8500c631dc32fa18645b7436344a99e4825e10e",
  "0x1967d8af5bd86a497fb3dd7899a020e47560daaf",
  "0xed6e0a7e4ac94d976eebfb82ccf777a3c6bad921",
  "0xa7e5d5a720f06526557c513402f2e6b5fa20b008",
  "0x6b69e2a7545c166417a80c61a77562052bffa9c5",
  "0x2711d73d559f62f4f855ee21f38378f528e07985",
  "0x530a64c0ce595026a4a556b703644228179e2d57",
  "0x6f1ca141a28907f78ebaa64fb83a9088b02a8352",
  "0xf2235d55b2950a0b1317469d72d07ae65b2e27cb",
];
